name: ekos
description: "Kırıkkale University Econometrics and E-Sports Community Phone Mobile Application."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^0.13.3
  shared_preferences: ^2.0.6
  provider: ^6.0.1
  url_launcher: ^6.1.14
  firebase_core: ^2.3.0
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.17.5
  firebase_messaging: ^14.7.10
  permission_handler: ^10.2.0
  firebase_database: ^10.4.8
  signature: ^4.0.0
  crypto: ^3.0.1
  path_provider: ^2.0.11
  pdf: ^3.4.1
  open_file: ^3.2.1
  package_info_plus: ^4.1.0
  intl: ^0.18.0
  flutter_email_sender: ^7.0.0
 
  
 

  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.11.0 

flutter:
  uses-material-design: true

  # Görsel tanımlaması
  assets:
    - assets/images/icon_logo.png
    - assets/images/kkulogo.png
    - assets/images/ekoslogo.png
    - assets/images/academic advisor of the community.png
    - assets/images/leader.png
    - assets/images/tufanexe.png
    - assets/images/güven_aralığı.png
    - assets/images/guide1.png
    - assets/images/guide2.png
    - assets/images/avast.png
    - assets/images/bit.png   
    - assets/images/avg.png
    - assets/images/kaspersky.png
    - assets/gifs/spinningfish.gif
    - assets/images/communitychat.png


    

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon_logo.png"